nginx:
  replicaCount: 3
  image:
    image: 381492128216.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-nginx
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources: {}

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  mysqlRootPassword: rootpassword123
  service:
    type: ClusterIP
    port: 3306
  resources: {}